orin-robo: 
  host: iilab47.labs.tno.nl
  user: dev
  gitpath: /home/leeuwenmcv/git/

laptop-cv90:
  host: iilab41.labs.tno.nl
  user: leeuwenmcv
  gitpath: /home/leeuwenmcv/git/

dl-3:
  host: pc-11393.tsn.tno.nl
  user: leeuwenmcv
  port: 10003
  datapath: /uhome/leeuwenmcv/data/
  gitpath: /uhome/leeuwenmcv/git/


dl-11:
  host: pc-11393.tsn.tno.nl
  user: leeuwenmcv
  port: 10011
  datapath: /uhome/leeuwenmcv/data/
  gitpath: /uhome/leeuwenmcv/git/
  project: spear

dl-41:
  host: pc-11393.tsn.tno.nl
  user: leeuwenmcv
  port: 10041
  datapath: /uhome/leeuwenmcv/data/
  gitpath: /uhome/leeuwenmcv/git/

toren:
  host: pc-08680.tsn.tno.nl
  user: leeuwenmcv
  datapath: /data/leeuwenmcv/
  gitpath: /uhome/leeuwenmcv/git/

spear-jetson-root:
  host: iilab42.labs.tno.nl
  user: nvidia
  datapath: /home/nvidia/data
  gitpath: /home/nvidia/git/
  project: spear

spear-jetson:
  host: iilab42.labs.tno.nl
  user: leeuwenmcv
  datapath: /home/leeuwenmcv/data
  gitpath: /home/leeuwenmcv/git/
  project: spear

spear-yellow:
  host: srv.delftdynamics.nl
  user: tno
  port: 1140
  datapath: /home/tno/data
  gitpath: /home/tno/git/
  project: spear


spear-blue:
  host: srv.delftdynamics.nl
  user: tno
  port: 1142
  datapath: /home/tno/data
  gitpath: /home/tno/git/
  project: spear


spear-green:
  host: srv.delftdynamics.nl
  user: tno
  port: 1144
  datapath: /home/tno/data
  gitpath: /home/tno/git/
  project: spear

spear-exp-blue:
  host: 192.168.1.142
  user: tno
  port: 22
  datapath: /home/tno/data
  gitpath: /home/tno/git/
  project: spear

spear-exp-green:
  host: 192.168.1.144
  user: tno
  port: 22
  datapath: /home/tno/data
  gitpath: /home/tno/git/
  project: spear

spear-exp-yellow:
  host: 192.168.1.140
  user: tno
  port: 22
  datapath: /home/tno/data
  gitpath: /home/tno/git/
  project: spear

startlight4:
  host: starlight4
  user: leeuwenmcv
  datapath: /data/leeuwenmcv/
  gitpath: /home/leeuwenmcv/git/
  project: schiphol_reid

reidpc:
  host: pc-08682.tsn.tno.nl
  user: reid
  datapath: /data/reid/
  gitpath: /home/reid/git/
  project: schiphol_reid



orin-gold:
  host: iilab29.labs.tno.nl
  user: dev
  datapath: /data/dev/
  gitpath: /home/dev/git/
  project: v2119

orin-mantis:
  host: iilab56.labs.tno.nl
  user: leeuwenmcv
  datapath: /data/leeuwenmcv/
  gitpath: /home/leeuwenmcv/git/
  project: mantis

orin-mantis-b:
  host: iilab32.labs.tno.nl
  user: dev
  datapath: /data/leeuwenmcv/
  gitpath: /home/leeuwenmcv/git/
  project: mantis

xavier2-ib:
  host: iilab22.labs.tno.nl
  user: ibotics
  datapath: /data/ibotics/
  gitpath: /home/ibotics/git/
  project: v2119

xavier1-ib:
  host: iilab24.labs.tno.nl
  user: dev
  datapath: /data/dev/
  gitpath: /home/dev/git/
  project: v2119

avalor-jetson:
  host: "5.159.32.215"
  user: tno
  port: 61234
  gitpath: /home/tno/git/
  datapath: /home/tno/data/
  project: spear/pipeline

linux-pc:
  host: "192.168.2.6"
  user: martin
  gitpath: /home/martin/git
  datapath: /home/martin/git


# Passwd EdgeAI2023
