orin-gold:
  host: iilab29.labs.tno.nl
  user: dev
  datapath: /data/dev/
  gitpath: /home/dev/git/
  project: v2119

orin-mantis:
  host: iilab52.labs.tno.nl
  user: dev
  datapath: /data/dev/
  gitpath: /home/dev/git/
  project: v2119
