mantis-pc31:
  host: pc-11393.tsn.tno.nl
  user: leeuwenmcv
  port: 31000
  datapath: /data/leeuwenmcv/mantis/
  gitpath: /uhome/leeuwenmcv/git/mantis/
  project: mantis

spear-jetson:
  host: iilab42.labs.tno.nl
  user: nvidia
  datapath: /home/nvidia/data
  gitpath: /home/nvidia/git/spear
  project: spear

spear-delft-dynamics-jetson:
  host: srv.delftdynamics.nl 
  user: tno
  port: 1140
  datapath: /home/tno/data
  gitpath: /home/tno/proj/






